### ISSUE TITLE
Time Complexity

### ISSUE THREAD

**Issue by whoisfreaks-user** [rockdaboot/libpsl#204]
Actually both of your findRules implementations(ArrayIndex and TreeIndex) took too long to search because of their time complexities which are O(N) and O(logN). Can't you reduce to O(1) by using Java Maps, which will be more efficient.

**Comment by rockdaboot** [comment]
This project is not written in Java, so no Java HashMap 😄 

Just for the background, the two current lookup algorithms are

a) Prefix+Suffix tree (DAFSA) stored as a blob. This is very space-efficient (54k) and doesn't need to be parsed on load. The lookups are not super fast, but this is perfectly ok for relatively low number of lookups.

b) Sorted arrays with binary search. On data loading, it requires parsing of the input and constructing the arrays. This is quite a big overhead. Once constructed, the lookup complexity is logN, as you say. Since in the public suffix list are currently only ~9500 entries, that is 9 (not counting the constant factor in the complexity). That is relatively fast (1000x faster than solution a)). I did not measure the memory impact, but would calculate at least 148*9500 bytes in up to 9500 chunks of heap memory (~1.4MB).

As you say, using hash maps reduces the complexity to 1. This could in theory increase the lookup time by a factor of 9. But I assume a smaller factor, as calculating hashes over the full length of input strings is not for free.

If you have time to come up with a PR implementing a hashmap lookup, that would be cool.

Out of curiosity: What is your use case where the current logN complexity isn't fast enough ?
