### ISSUE TITLE
cmake support

### ISSUE THREAD

**Issue by NahuFigueroa97** [rockdaboot/libpsl#227]
Hello rockdaboot! Great job! congratulations! I'm trying to use this in my C++ project. I use cmake to build it, but I see that you use make.
Inside my CMakeLists.txt I have download your project using CPMAddPackage:

```
CPMAddPackage(
     NAME psl
     GITHUB_REPOSITORY rockdaboot/libpsl
     GIT_TAG ba4c49a205408845834b1648ad23c15ee09f722b # Latest master commit from 01/13/2024
     VERSION 0.21.5
)
```

and then I have to link your library in my project. Could you tell me if I'm correct? Do I need any more steps? My idea is to make a wrapper for c++

**Comment by eli-schwartz** [comment]
You should be able to tell cmake to execute `meson setup` instead of `./configure`

https://mesonbuild.com

Meson is quite portable to Windows, so it should work fine for your use cases.

...

I'm unfamiliar with CPMAddPackage, but I know that for CMake's own external project support, you do need to specify the command used to build an external project, if that project uses a build system other than cmake -- in this case, meson.

**Comment by rockdaboot** [comment]
@NahuFigueroa97 If you didn't succeed with meson, feel free to reopen.
