### ISSUE TITLE
Release tarball is broken

### ISSUE THREAD

**Issue by cicku** [rockdaboot/libpsl#28]
autoreconf on release tarball(not github source):

configure.ac:40: error: required file 'docs/libpsl/Makefile.in' not found
configure.ac:40: error: required file 'docs/libpsl/version.xml.in' not found
src/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1

Also, the configure script included in release tarball includes RPATH, which is a potential security risk.

**Comment by rockdaboot** [comment]
I guess I need some help:

1.
make distcheck succeeds, a subsequent make dist generates a broken tarball...
(Maybe I make wrong assumptions about what 'make distcheck' is for ?)

2.
Depending on the system and environment, a tarball seems to be different. This is not consistent.
Also, a tarball is redundant (taking the git sources seems much clearer when building a package).
Obviously, you and I are wasting our time with tarballs.
Wouldn't it be reasonable to drop tarballs at all (someone asked for it, that's why I provide it).

3. I can't see any RPATH included !? From what I can read, the RPATH problem should have been buried since 2004 !? Maybe you can give me a second hint on this.

**Comment by rockdaboot** [comment]
I replaced the tarball with one including the compiled docs. That's ugly but should work for you.
I am waiting for more RPATH info from you until I close the issue.

**Comment by rockdaboot** [comment]
Got no more info from you.
