### ISSUE TITLE
build problems on OS X

### ISSUE THREAD

**Issue by gaming-hacker** [rockdaboot/libpsl#34]
libidn and icu4 are installed by homebrew and exist but configure doesn't find them and so i turned them off with

--disable-runtime --disable-builtin

make gives following error

psl.c:90:10: fatal error: 'bits/stat.h' file not found
#include <bits/stat.h>
         ^
1 error generated.
Makefile:510: recipe for target 'libpsl_la-psl.lo' failed

any help?

**Comment by rockdaboot** [comment]
Just remove the include line :-) It has already been fixed in branch 'develop'.
Sorry for that, I still don't know how that line managed to go into the source - must have been some experiment by me and I just forgot to remove it.

But I am very interested in why libidn and libicu aren't found. Do you have pkg-config installed ?

**Comment by gaming-hacker** [comment]
cool, thanks for the fix

yes, latest version 0.29, teh only way to get it to recognize idn was to export LDFLAGS
