### ISSUE TITLE
Untrusted input

### ISSUE THREAD

**Issue by daurnimator** [rockdaboot/libpsl#59]
From comments:
> International domain names have to be either in lowercase UTF-8 or in ASCII form (punycode).
> Other encodings result in unexpected behavior.

What sort of unexpected behaviour do you mean here?
e.g. What happens if I gave it uppercase characters? What happens if I give it a string with malformed utf-8?

**Comment by rockdaboot** [comment]
Github auto-closing... ok, wanted to thank you for your work/issues !

**Comment by daurnimator** [comment]
You changed it to
>  Other encodings likely result in incorrect return values.

That still doesn't answer the question... 
What happens with upper case values? Why mention lower case at all? What happens if the input has control characters? Do you safely handle malformed utf8?

**Comment by rockdaboot** [comment]
Your first question was about 'unexpected behavior'.
I agree, that is very vague (e.g. would include segfaults and other 'crashes').
To your other questions: Stuff is handled gracefully.
Just don't expect uppercase input to return an 'expected' value. Let's assume 'übel.de' would be a public suffix. While psl_is_public_suffix('übel.de') returns 1, psl_is_public_suffix('Übel.de') will likely return 0. Same goes to malformed UTF-8 input.

The functions are designed to work on lowercase UTF-8 because domain names are distinguished on lower case basis. Whenever an application gets a domain name/label as input, it will 'normalize' the input before doing further checks (lower casing is just one normalization). Depending on the input encoding, this might be a (relatively) slow process. To have the best possible performance experience, libpsl does not automatically do lowercasing and transformation to UTF-8. But it provides `psl_str_to_utf8lower()` to exactly do this, if you don't have your own routine. Using the libpsl function helps to avoid linking with two different IDN libraries (e.g. libpsl might be built against libicu and your application against libidn). If there is anything missing where you think it should go into libpsl, let me know (open a new issue).

Should any of this text go into the docs ? WDYT ?

**Comment by daurnimator** [comment]
> Should any of this text go into the docs ? WDYT ?

I think being a bit more explicit about what sort of 'incorrect return values' to expect would be good.
I'd also explicitly call out that `psl_str_to_utf8lower` should be used when you're not already sure about the case.
