### ISSUE TITLE
Getting more detailed error information

### ISSUE THREAD

**Issue by daurnimator** [rockdaboot/libpsl#68]
I'd like to be able to get explanatory errors from various libpsl functions.

With the current style of the library, manually setting of `errno` would probably be the most sensible path to take:

Going through `psl_load_file`:
  - in the `fname==NULL` case no `errno` is set;
  - if `fclose` fails it would overwrite errno

Going deeper into `psl_load_fp`:
  - outside of glibc `calloc`, `malloc`, etc. may not set `errno`
  - `fread` would need `ferror` to get the error

Outside of those constructors, the encoding libraries often have more information (e.g. reason behind `PSL_ERR_CONVERTER`): it'd be nice to get this info.

**Comment by rockdaboot** [comment]
> in the fname==NULL case no errno is set;
> if fclose fails it would overwrite errno

There is no general way to set errno (e.g. might be a function).
Since there might be more than one error within a function, how would you like to receive these ?
Do you would like to provide a callback function ?
Then, on ferror() errno is not set... what does your function receive (maybe it won't have any arguments ? Possibly you like to provide a printf-type callback function ?)
Same with errors on functions to external libs... how should their own error/status codes map to libpsl and yours ?

Since you are currently the only one with a possible use case, please provide a detailed plan.

**Comment by daurnimator** [comment]
> There is no general way to set errno (e.g. might be a function).

You can do `errno = ENOMEM`.

From [errno(3)](https://linux.die.net/man/3/errno):
>For some system calls and library functions (e.g., getpriority(2)), -1 is a valid return on success. In such cases, a successful return can be distinguished from an error return by setting errno to zero before the call, and then, if the call returns a status that indicates that an error may have occurred, checking to see if errno has a nonzero value.
>
> errno is defined by the ISO C standard to be a modifiable lvalue of type int, and must not be explicitly declared; errno may be a macro. errno is thread-local; setting it in one thread does not affect its value in any other thread.

**Comment by rockdaboot** [comment]
Read your initial post. Fclose fails after a first error hapens and than what. Would you like To See first, second or both error conditions ? Just errno might not be enough. What about status codes from e.g. libicu ? I am not going to map them to errno. A printf style callback could receive detailed messages for logging.

**Comment by rockdaboot** [comment]
Not stopping on first error is quite common. That is called fallback, e.g. a second try on EINTR or a different method for a task if the first one fails.

**Comment by daurnimator** [comment]
> Read your initial post. Fclose fails after a first error hapens and than what. Would you like To See first, second or both error conditions ?

Usually (and in this case), the first one.

>  e.g. a second try on EINTR or a different method for a task if the first one fails.

Not all errno values are errors. e.g. EINTR and EAGAIN are returned *via* errno, but should not (usually) be considered error conditions. In any case, those should be taken care of by libc for us.

> What about status codes from e.g. libicu ? I am not going to map them to errno.

Why not?
But in that case, just map them all to

**Comment by rockdaboot** [comment]
> Usually (and in this case), the first one.

Since errno has to be saved and restored, I begin to wonder when errno became thread-local and if that works on non POSIX platforms as well.

>> What about status codes from e.g. libicu ? I am not going to map them to errno.

>> e.g. a second try on EINTR or a different method for a task if the first one fails.

> Not all errno values are errors. e.g. EINTR and EAGAIN are returned via errno, but should not (usually) be considered error conditions. In any case, those should be taken care of by libc for us.

The app has to take care of it. These are special error conditions (usually) worth a retry by the app code, but at some point there will be a error return (usually when a certian number of retries is exceeded). 

> Why not?
> But in that case, just map them all to EINVAL, most of the possible errors are effectively bad input

Those status codes are already mapped to a single PSL error code.

I still believe that manipulating errno is tedious, superfluous, error-prone, information leaking.
A callback printf-style e.g. set when 'debug mode' is requested on application side seems to be much more informative.

**Comment by daurnimator** [comment]
> Since errno has to be saved and restored

Huh? The only time you need to save/restore `errno` is in a signal handler.

> I begin to wonder when errno became thread-local and if that works on non POSIX platforms as well.

It became thread local at the time of the introduction of threads :) Otherwise you would break all threaded programs that use `errno`.
On the only major non-POSIX platform (windows) you have functions `GetLastError()` and `SetLastError()` which perform the same functionality as `errno` (and are likewise thread-safe)

**Comment by rockdaboot** [comment]
>> Since errno has to be saved and restored

> Huh? The only time you need to save/restore errno is in a signal handler.

You brought this up in your initial post: "if fclose fails it would overwrite errno".
Which implies, errno has to be saved and restored if an error happens before we call fclose().
So please argue on that or say that you are dropping that idea.

> It became thread local at the time of the introduction of threads :) Otherwise you would break all threaded programs that use errno.

I remember times where threading was available, but errno (and some other stuff) still was static. Times of headaches resp. times of mutexes everywhere resp. avoidance of threads.

> On the only major non-POSIX platform (windows) you have functions GetLastError() and SetLastError() which perform the same functionality as errno (and are likewise thread-safe)

Just my saying, using errno is not portable.
