### ISSUE TITLE
builtin vs. latest in help output of psl cli

### ISSUE THREAD

**Issue by andreasstieger** [rockdaboot/libpsl#76]
The way I understand https://github.com/rockdaboot/libpsl/commit/ff29f13d8fd3a18ded5145ca61fb69e52ab9a9d7#diff-6f75143751c2304faf253f5f89a0b441 is that this changes the default from using the built-in file to the latest

``  --use-builtin-data           use the builtin PSL data [default]``

Is the built-in data still the default?

**Comment by rockdaboot** [comment]
Oh. I did that change without thinking enough, I guess.
Regarding docs and backwards compatibility the commit is a bug.

With psl_latest() available, the builtin data became a 'fallback' when there is no or only outdated PSL data available otherwise. I guess a --use-latest-data should be added as default. WDYT ?
